name: LegacyKB
version: ${project.version}
main: org.abyssmc.legacykb.LegacyKB
authors: [DefineOutside]
description: A simple knockback plugin that works.
commands:
  legacykb:
    description: /legacykb reload - to reload the plugin
    permission: kohikb.reload
permissions:
  kohikb.reload:
    description: /legacykb reload - to reload the plugin
    default: op
  legacykb.*:
    description: Wildcard permission
    default: op
    children:
      legacykb.reload: true